package ai.hans.standard.diagnostics

import java.util.Locale

/**
 * Local-only diagnostic metadata. This type cannot carry tool arguments, output, exception
 * messages, tokens, app names or identifiers. Unknown producer values are deliberately discarded.
 * Never serialize this metadata into the App Server's dynamic-tool result wire contract.
 */
data class ToolFailureDiagnostic(
    val code: ToolFailureCode,
    val detail: ToolFailureDetail? = null,
) {
    companion object {
        fun fromCodes(code: String?, detail: String? = null): ToolFailureDiagnostic =
            ToolFailureDiagnostic(
                code = ToolFailureCode.fromCode(code),
                detail = detail?.let(ToolFailureDetail::fromCode),
            )
    }
}

/** Only reviewed, exact producer literals enter the recording; syntactic validity is not enough. */
enum class ToolFailureCode {
    UNKNOWN,
    DYNAMIC_TOOL_EXCEPTION,
    DYNAMIC_TOOL_FAILURE,
    EXECUTOR_REJECTED,
    UNKNOWN_DYNAMIC_TOOL,
    INVALID_ARGUMENTS,
    TOOL_OUTPUT_TOO_LARGE,
    DEVICE_UNLOCK_REQUIRED,
    SCREEN_WAKE_REQUIRED,
    DEVICE_WAKE_AND_UNLOCK_REQUIRED,
    DEVICE_UI_STATE_VERIFICATION_REQUIRED,
    ACCESSIBILITY_PERMISSION_REQUIRED,
    ACCESSIBILITY_SERVICE_RECONNECTING,
    ACCESSIBILITY_SESSION_CLOSED,
    ACCESSIBILITY_SESSION_UNAVAILABLE,
    ACCESSIBILITY_QUEUE_FULL,
    SESSION_EXECUTION_FAILED,
    UI_SNAPSHOT_TEMPORARILY_UNAVAILABLE,
    UI_SNAPSHOT_UNAVAILABLE,
    UI_SEQUENCE_BUSY,
    UI_SEQUENCE_CAPACITY_EXHAUSTED,
    UI_SEQUENCE_CONTEXT_UNAVAILABLE,
    UI_SEQUENCE_CANCELLED_OR_CONTEXT_CHANGED,
    UI_SEQUENCE_DEADLINE_EXCEEDED,
    UI_SEQUENCE_REPLAYED_STEP_STOPPED,
    UI_SEQUENCE_EXECUTION_FAILED,
    UI_TARGET_WAIT_EXPIRED,
    UI_TARGET_UNAVAILABLE,
    UI_TARGET_SNAPSHOT_UNAVAILABLE,
    UI_TARGET_SNAPSHOT_INCOMPLETE,
    UI_TARGET_AMBIGUOUS,
    SNAPSHOT_SOURCE_FAILED,
    SNAPSHOT_UNAVAILABLE,
    SEMANTIC_FALLBACK_PROOF_REQUIRED,
    IDEMPOTENCY_KEY_CONFLICT,
    STALE_SNAPSHOT,
    STALE_SESSION,
    STALE_NODE_HANDLE,
    NODE_NOT_FOUND,
    NODE_NOT_VISIBLE,
    NODE_NOT_ENABLED,
    NODE_NOT_CLICKABLE,
    NODE_CLICK_UNSUPPORTED,
    NODE_NOT_EDITABLE,
    NODE_SET_TEXT_UNSUPPORTED,
    NODE_NOT_SCROLLABLE,
    NODE_SCROLL_UNSUPPORTED,
    GESTURE_START_OUT_OF_BOUNDS,
    GESTURE_END_OUT_OF_BOUNDS,
    COORDINATE_GESTURE_UNSUPPORTED,
    RISK_POLICY_FAILED,
    CONFIRMATION_REQUIRED,
    CONFIRMATION_DENIED,
    CONFIRMATION_EXPIRED,
    CONFIRMATION_CONTEXT_CHANGED,
    CONFIRMATION_UNAVAILABLE,
    DICTATION_GUARD_UNAVAILABLE,
    DICTATION_LIFECYCLE_INTERFERENCE,
    ADAPTER_EXCEPTION,
    ADAPTER_STALE_TARGET,
    ADAPTER_ACTION_UNSUPPORTED,
    ADAPTER_RECEIPT_INVALID,
    ADAPTER_RECEIPT_UNTRUSTED,
    ADAPTER_POSTCONDITION_UNTRUSTED,
    ADAPTER_POSTCONDITION_INVALID,
    ADAPTER_CORRELATION_MISMATCH,
    ADAPTER_SESSION_MISMATCH,
    ANDROID_LOCATOR_RECEIPT_MISSING,
    POSTCONDITION_BASELINE_UNAVAILABLE,
    POSTCONDITION_SNAPSHOT_UNAVAILABLE,
    POSTCONDITION_NOT_VERIFIED,
    ANDROID_GLOBAL_ACTION_BLOCKED,
    ANDROID_GLOBAL_ACTION_CANCELLED,
    ANDROID_GLOBAL_ACTION_TIMED_OUT,
    ANDROID_GLOBAL_ACTION_FAILED,
    ANDROID_GLOBAL_ACTION_RECEIPT_INVALID,
    ANDROID_GESTURE_BLOCKED,
    ANDROID_GESTURE_CANCELLED,
    ANDROID_GESTURE_TIMED_OUT,
    ANDROID_GESTURE_FAILED,
    ANDROID_GESTURE_RECEIPT_INVALID,
    ANDROID_NODE_ACTION_BLOCKED,
    ANDROID_NODE_ACTION_CANCELLED,
    ANDROID_NODE_ACTION_TIMED_OUT,
    ANDROID_NODE_ACTION_FAILED,
    ANDROID_NODE_ACTION_RECEIPT_INVALID,
    VISUAL_CAPTURE_UNAVAILABLE,
    VISUAL_CAPTURE_FAILED,
    VISUAL_CAPTURE_MAIN_THREAD_REJECTED,
    VISUAL_CAPTURE_BUSY,
    VISUAL_CAPTURE_CAPABILITY_UNAVAILABLE,
    VISUAL_CAPTURE_DISPLAY_UNAVAILABLE,
    VISUAL_CAPTURE_ENCODING_FAILED,
    VISUAL_CAPTURE_REQUEST_FAILED,
    VISUAL_CAPTURE_TIMED_OUT,
    VISUAL_CAPTURE_CALLBACK_MISSING,
    VISUAL_CAPTURE_CONTENT_CHANGED,
    VISUAL_CAPTURE_ACCESS_REVOKED,
    VISUAL_CAPTURE_RATE_LIMITED,
    VISUAL_CAPTURE_INVALID_DISPLAY,
    VISUAL_CAPTURE_INTERNAL_ERROR,
    VISUAL_CAPTURE_PLATFORM_REJECTED;

    val wire: String = name.lowercase(Locale.ROOT)

    companion object {
        private val byCode = entries.associateBy(ToolFailureCode::wire)

        fun fromCode(code: String?): ToolFailureCode = when (code) {
            // Exact known variants only: never accept an arbitrary attacker-controlled suffix.
            "confirmation_required_none",
            "confirmation_required_external_communication",
            "confirmation_required_destructive",
            "confirmation_required_credential_ui",
            -> CONFIRMATION_REQUIRED
            else -> byCode[code] ?: UNKNOWN
        }
    }
}

enum class ToolFailureDetail {
    UNKNOWN,
    PROOF_MISSING_OR_CONSUMED,
    PROOF_EXPIRED,
    PROOF_THREAD_MISMATCH,
    PROOF_TURN_MISMATCH,
    PROOF_CORRELATION_MISMATCH,
    PROOF_CURRENT_SNAPSHOT_MISMATCH,
    PROOF_ALREADY_CLAIMED,
    PROOF_EVIDENCE_EPOCH_CHANGED,
    DISPLAY_UNAVAILABLE,
    DISPLAY_INVALID,
    DISPLAY_CONTEXT_FAILED,
    NO_ACTIVE_ROOT,
    INVALID_WINDOW,
    DISPLAY_BOUNDS_FAILED,
    PROJECTION_ROOT_READ_FAILED,
    PROJECTION_EMPTY,
    PROJECTION_FAILED,
    SNAPSHOT_FACTORY_FAILED,
    SNAPSHOT_PUBLICATION_FAILED,
    SNAPSHOT_ID_EXHAUSTED,
    CAPTURE_FAILED,
    SNAPSHOT_FAILURE_UNCLASSIFIED,
    REQUEST_REJECTED,
    USER_ACTION_REQUIRED,
    CONFIRMATION_REQUIRED,
    ADAPTER_OPERATION_FAILED,
    DICTATION_LIFECYCLE_INTERFERENCE,
    ACCESSIBILITY_SESSION_CLOSED,
    SESSION_EXECUTION_FAILED;

    val wire: String = name.lowercase(Locale.ROOT)

    companion object {
        private val byCode = entries.associateBy(ToolFailureDetail::wire)
        fun fromCode(code: String): ToolFailureDetail = byCode[code] ?: UNKNOWN
    }
}
